apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data: # base64 encode with cli @ echo mongouser | base64 , echo mongopassword | base64
  mongo-user: bW9uZ291c2Vy # encoded with base64
  mongo-password: bW9uZ29wYXNzd29yZA== # encoded with base64

